AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yahoo-fantasy

  Sample SAM Template for yahoo-fantasy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DomainName:
    Type: String
    Description: your website domain name
    Default: fantasy.laohuang.org
  ProjectName:
    Type: String
    Description: your project name
    Default: yahoo-fantasy
  ClientId:
    Type: String
    Description: the yahoo applicaiton client id
    Default: id
  ClientSecret:
    Type: String
    Description: the yahoo applicaiton client secrect
    Default: secrect

Resources:
  LambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        -
          PolicyName: 'LambdaLogging'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !GetAtt LambdaLogGroup.Arn
        -
          PolicyName: 'LambdaDynamoDBAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'dynamodb:*'
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}'
        -
          PolicyName: 'LambdaS3Access'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${DomainName}'
              -
                Effect: Allow
                Action:
                  - 's3:*'
                Resource: !Sub 'arn:aws:s3:::${DomainName}/data/*'
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProjectName}"
      RetentionInDays: 1

  WebServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: web-server/
      Handler: app.lambda_handler
      Runtime: python3.11
      FunctionName: !Sub ${ProjectName}-web-server
      Architectures:
        - x86_64
      Events:
        LoginApiEvent:
          Type: HttpApi
          Properties:
            Path: /login
            Method: get
        CallbackApiEvent:
          Type: HttpApi
          Properties:
            Path: /callback
            Method: get
        LeaguesApiEvent:
          Type: HttpApi
          Properties:
            Path: /api/leagues
            Method: get
        AnalyzeApiEvent:
          Type: HttpApi
          Properties:
            Path: /api/analyze
            Method: post
        PollingApiEvent:
          Type: HttpApi
          Properties:
            Path: /api/polling
            Method: post
      Environment:
        Variables:
          CLIENT_ID:  !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
          DB_SESSION_TABLE: !Sub ${ProjectName}-session
          DB_TASK_TABLE: !Sub ${ProjectName}-task
          S3_BUCKET_NAME: !Ref DomainName
          BASE_URL: !Sub https://${DomainName}
      Role: !GetAtt LambdaExecRole.Arn
  AnalyzeTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      FunctionName:  !Sub ${ProjectName}-analyze-task
      Architectures:
        - x86_64
      Environment:
        Variables:
          CLIENT_ID:  !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
          DB_SESSION_TABLE: !Sub ${ProjectName}-session
          DB_TASK_TABLE: !Sub ${ProjectName}-task
          S3_BUCKET_NAME: !Ref DomainName
          BASE_URL: !Sub https://${DomainName}
      Role: !GetAtt LambdaExecRole.Arn
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./analyze-task
      DockerTag: python3.11-v1
  SessionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub ${ProjectName}-session
      AttributeDefinitions:
        - AttributeType: "S"
          AttributeName: "sessionId"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "sessionId"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: "expireAt"
  TaskTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub ${ProjectName}-task
      AttributeDefinitions:
        - AttributeType: "S"
          AttributeName: "taskId"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "taskId"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: "expireAt"
  # StaticWebSiteS3Bucket:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     BucketName: !Ref ProjectName
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - BucketKeyEnabled: true
  #           ServerSideEncryptionByDefault:
  #             SSEAlgorithm: "AES256"
  #     WebsiteConfiguration:
  #       IndexDocument: "index.html"
  #       ErrorDocument: "error.html"
  #     AccessControl: Private
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket:
  #       Ref: "StaticWebSiteS3Bucket"
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #       - Condition:
  #           ArnEquals:
  #             SourceArn:
  #               Fn::GetAtt:
  #               - "CloudFrontDistribution"
  #               - "Arn"
  #         Effect: Allow
  #         Principal:
  #           Service: "cloudfront.amazonaws.com"
  #         Action: 's3:GetObject'
  #         Resource: !Sub '${StaticWebSiteS3Bucket.Arn}/*'
  # CloudFrontOriginIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: 'origin identity'
  # CloudFrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       DefaultRootObject: "index.html"
  #       Origins:
  #         - DomainName:
  #             Fn::GetAtt:
  #             - "StaticWebSiteS3Bucket"
  #             - "RegionalDomainName"
  #           S3OriginConfig:
  #             OriginAccessIdentity: ""
  #           # OriginPath: ""
  #           Id: "fantasy.laohuang.org.s3.us-east-1.amazonaws.com"
  #       Enabled: 'true'
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - GET
  #           - HEAD
  #         TargetOriginId: "fantasy.laohuang.org.s3.us-east-1.amazonaws.com"
  #         ForwardedValues:
  #           QueryStringCacheKeys: []
  #           Cookies:
  #             Forward: "all"
  #           Headers: []
  #           QueryString: true
  #         ViewerProtocolPolicy: redirect-to-https
  #       ViewerCertificate:
  #         MinimumProtocolVersion: "TLSv1.2_2021"
  #         SslSupportMethod: "sni-only"
  #         AcmCertificateArn: "arn:aws:acm:us-east-1:711387121254:certificate/2e1c3799-2a39-4d43-906d-6fd5824344f7"

