# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "yahoo-fantasy"

[default.build.parameters]
cached = true
parallel = true
exclude = ["*.dist-info/*"]

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "yahoo-fantasy"
region = "us-east-1"
image_repositories = ["WebServerFunction=711387121254.dkr.ecr.us-east-1.amazonaws.com/yahoofantasyd3915317/webserverfunction119ea898repo", "LongRunningJobFunction=711387121254.dkr.ecr.us-east-1.amazonaws.com/yahoofantasyd3915317/longrunningjobfunctionc27544f8repo"]
parameter_overrides = "ClientId=\"dj0yJmk9VUFhM1Zab1QwT2QzJmQ9WVdrOVVVbGhNa0ZtUkRRbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTAw\" ClientSecret=\"b387ea999b6615b308c8a67fd3ea70f778e8703a\" AlternateDomainName=\"fantasy.laohuang.org\" SSLCertificateArn=\"arn:aws:acm:us-east-1:711387121254:certificate/2e1c3799-2a39-4d43-906d-6fd5824344f7\" HostedZoneId=\"Z00026602M1LG268PQ0LG\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
